// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnCaE1Hm6FyRI1ftDywgxNk1i9n67yaA0',
    appId: '1:688947131707:web:bfe831c30dfe11daf0b31e',
    messagingSenderId: '688947131707',
    projectId: 'smartbinnotification-12846',
    authDomain: 'smartbinnotification-12846.firebaseapp.com',
    storageBucket: 'smartbinnotification-12846.appspot.com',
    measurementId: 'G-CWP4VLG77Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRf-K7qMJGtjFBASDLPkP1q2AnBZEQDEQ',
    appId: '1:688947131707:android:b76a2f17fa0d5c92f0b31e',
    messagingSenderId: '688947131707',
    projectId: 'smartbinnotification-12846',
    storageBucket: 'smartbinnotification-12846.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-E0n8rniv28bhoSo-BAm-cQ9sK5wm9Xo',
    appId: '1:688947131707:ios:be1dcadde2408411f0b31e',
    messagingSenderId: '688947131707',
    projectId: 'smartbinnotification-12846',
    storageBucket: 'smartbinnotification-12846.appspot.com',
    iosClientId: '688947131707-tf05vcdmegmsqi7jqgq0aj7vcm7uu892.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-E0n8rniv28bhoSo-BAm-cQ9sK5wm9Xo',
    appId: '1:688947131707:ios:be1dcadde2408411f0b31e',
    messagingSenderId: '688947131707',
    projectId: 'smartbinnotification-12846',
    storageBucket: 'smartbinnotification-12846.appspot.com',
    iosClientId: '688947131707-tf05vcdmegmsqi7jqgq0aj7vcm7uu892.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBin',
  );
}
